### ISSUE TITLE
Проблема с установкой poetry на Ubuntu с версией python <3.7

### ISSUE THREAD

**Issue by ProValdi** [FrCln/bookkeeper#1]
Это небольшой гайд для тех, кто так же как и я столкнулся с проблемой установки poetry на свои Linux-OS с версией python <3.7, чтобы сократить возможное время решения проблемы.

# Пререквизиты

Установленная ОС с ядром Linux:
```
$: lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

```
Версия python:

```
$: python3 --version
Python 3.6.9
```

# Проблема

Попытка установить poetry командой с официального сайта:
```
$: curl -sSL https://install.python-poetry.org | python3 -
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/home/bob/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.3.2): An error occurred. Removing partial environment.
Poetry installation failed.
See /home/bob/git_projects/PYTHON_PROJECT/bookkeeper/poetry-installer-error-g5ewy0eb.log for error logs.

```
В логах указанного в ошибке файле не найдена версия poetry = 1.3.2 (только для версии python = "^3.7"):

```
ERROR: Could not find a version that satisfies the requirement poetry==1.3.2 (from versions: 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.4.0.post1, 0.4.1, 0.4.2, 0.5.0b1, 0.5.0b2, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3b1, 0.6.3b2, 0.6.3b3, 0.6.3b4, 0.6.3b5, 0.6.3b6, 0.6.3b7, 0.6.3, 0.6.4b1, 0.6.4, 0.6.5, 0.7.0b1, 0.7.0b2, 0.7.0b3, 0.7.0b4, 0.7.0, 0.7.1, 0.8.0a0, 0.8.0a1, 0.8.0a2, 0.8.0a3, 0.8.0a4, 0.8.0, 0.8.1a0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5a0, 0.8.5, 0.8.6, 0.9.0a0, 0.9.0a1, 0.9.0a2, 0.9.0a3, 0.9.0, 0.9.1, 0.10.0a0, 0.10.0a1, 0.10.0a2, 0.10.0a3, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0a0, 0.11.0a1, 0.11.0a2, 0.11.0a3, 0.11.0a4, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.11.4, 0.11.5, 0.12.0a0, 0.12.0a1, 0.12.0a2, 0.12.0a3, 0.12.0a4, 0.12.0a5, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 0.12.6, 0.12.7, 0.12.8, 0.12.9, 0.12.10, 0.12.11, 0.12.12, 0.12.13, 0.12.14, 0.12.15, 0.12.16, 0.12.17, 1.0.0a0, 1.0.0a1, 1.0.0a2, 1.0.0a3, 1.0.0a4, 1.0.0a5, 1.0.0b1, 1.0.0b2, 1.0.0b3, 1.0.0b4, 1.0.0b5, 1.0.0b6, 1.0.0b7, 1.0.0b8, 1.0.0b9, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.1.0a1, 1.1.0a2, 1.1.0a3, 1.1.0b1, 1.1.0b2, 1.1.0b3, 1.1.0b4, 1.1.0rc1, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.1.10, 1.1.11, 1.1.12, 1.1.13, 1.1.14, 1.1.15, 1.2.0a1, 1.2.0a2)
ERROR: No matching distribution found for poetry==1.3.2
```

# Решение

Необходимо установить python (очевидно) свежей версии 3.10:
```
sudo add-apt-repository universe
sudo apt update
sudo apt install python3.10
```

Важное замечание: `python3 --version` по-прежнему будет давать старую версию python, поэтому проблема всё ещё остаётся актуальной. Чтобы решить её без серьёзных последствий, лучшим решением будет добавить alias:

Откройте файл `~/.bashrc` и добавьте в него строчку:

```
alias python3="python3.10"
```

После чего выполните команду:

```
source ~/.bashrc
```

Теперь `python3 --version` даст нужный результат: `Python 3.10.10` и можно без проблем установить poetry.

Возможные последствия других вариантов можно почитать в комментариях ветки stackoverflow:
https://stackoverflow.com/questions/35991403/pip-install-unroll-python-setup-py-egg-info-failed-with-error-code-1

@FrCln

**Comment by FrCln** [comment]
@ProValdi да, этот вариант выглядит рабочим, но я предпочитаю другой.

Есть утилита [pyenv ](https://github.com/pyenv/pyenv)
Она позволяет максимально удобно работать с несколькими версиями python на Linux-системах. Впрочем, есть версия и для Windows и MacOs. Я сам ей пользуюсь уже давно, никаких проблем ни разу не было.

Инструкция по установке есть в README по ссылке выше, но я уточню пару моментов. Эта утилита при установке требуемой версии python компилирует ее из исходников, поэтому для корректной работы нужно установить дополнительные библиотеки. Инструкция также есть в их [репозитории](https://github.com/pyenv/pyenv/wiki#suggested-build-environment). Для Ubuntu/Debian команда выглядит так:
```sh
sudo apt update; sudo apt install build-essential libssl-dev zlib1g-dev \
libbz2-dev libreadline-dev libsqlite3-dev curl \
libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
```

В некоторых дистрибутивах может еще чего-то не хватать (например, git или gcc), если вдруг это случится, из сообщения об ошибке будет понятно, чего не хватает. Для использования pypy нужно еще установить llvm.

Саму pyenv можно установить с помощью готового скрипта:
```sh
curl https://pyenv.run | bash
```

После перезапуска терминала все должно работать.

Для установки нужной версии python:
```sh
pyenv install 3.10.10
```

Для использования этой версии в текущем каталоге:
```sh
pyenv local 3.10.10
```

Для использования этой версии всегда (кстати, рекомендую сделать именно так, чтобы никогда не использовать и случайно не испортить системный python):
```sh
pyenv global 3.10.10
```

Если для каких-то целей все-таки нужно использовать системный python, можно переключится на него для данного сеанса оболочки:
```sh
pyenv shell system
```

Небольшое замечание для тех, кто работает в WSL. Утилита представляет собой просто git-репозиторий, для работы ей нужен git. Важно: если включена автоматическая замена '\n' на '\r\n', все сломается. Ее следует отключить, если вдруг она включена:
```sh
git config --global core.autocrlf false
```

Правда, при этом может быть менее удобно работать с файлами в файловой системе windows. Но можно использовать разные настройки для разных репозиториев - для этого просто не указывать флаг `--global`.

**Comment by 78985** [comment]
Здравствуйте! Вопрос следующий:
На компе стоит винда, поэтому использую mingw64. Существует следующая проблема: poetry установлен, однако при попытке собрать проект через poetry install вылетает какая-то ошибка. Возможно, она связана с тем, что стоит старая версия python 3.9.10 (которая была необходима для работы), а для корректно работающего проекта требуется 3.10. Удалить старую версию я не могу, потому что на неё завязаны рабочие файлы. Логичной идеей было бы поставить pyenv, но он говорит, что не хватает git. При попытке же поставить git через pacman вылетает снова какая-то неизвестная ошибка. Как быть?
![image](https://user-images.githubusercontent.com/48051747/223043342-91b45b85-e0c1-40f3-b862-6b819ded6e20.png)

**Comment by 78985** [comment]
Вот что происходит при попытке установить git средствами mingw. При этом git на компе установлен, но mingw его не видит. Зато его видит git bash, но в нём не работает уже poetry.
![image](https://user-images.githubusercontent.com/48051747/223044882-8da804b9-57b9-4ffb-9d6c-b68c0a250ef2.png)
![image](https://user-images.githubusercontent.com/48051747/223044937-0443b84d-83ae-48c1-ac59-56891912f076.png)

**Comment by FrCln** [comment]
Под Windows следует использовать [другую версию](https://pyenv-win.github.io/pyenv-win/)

**Comment by FrCln** [comment]
Git под Windows тоже устанавливается не так. Нужно брать [отсюда](https://gitforwindows.org/).

**Comment by FrCln** [comment]
В конце концов в Windows можно просто взять и установить несколько версий python, скачав нужную версию с [официального сайта](https://www.python.org/downloads/windows/).

![2023-03-06_11-37-58](https://user-images.githubusercontent.com/54150197/223059384-185b876b-8adc-47e8-8a49-dcc9f30b26bb.png)

Из командной строки также можно запускать разные версии:
![image](https://user-images.githubusercontent.com/54150197/223059716-3e3646ad-171b-4fbb-8046-aefc9f98e2c0.png)

**Comment by 78985** [comment]
То есть, работать нужно в консоли cmd, я так понимаю?

**Comment by FrCln** [comment]
Это не имеет значения. Можно работать в MinGW, только git там не устанавливается так, как вы пытаетесь это сделать.

**Comment by 78985** [comment]
А как поменять используемый python в mingw (именно там у меня настроен poetry)? А то я, по указанию экспертов, поставил python 3.10 под винду, но теперь мне осталось этот путь запихнуть в mingw, где стоит старая версия python. В обход pyenv. Export path не работает, как видите
![image](https://user-images.githubusercontent.com/48051747/223516676-5ea05457-bffe-4ec7-835f-586ca160b432.png)
![image](https://user-images.githubusercontent.com/48051747/223516734-63fddff9-63b1-4629-981d-686bf2b2811b.png)

**Comment by FrCln** [comment]
В PATH указываются пути не к файлам, а к каталогам, в которых система будет искать исполняемые файлы. То есть не надо писать python.exe.

**Comment by 78985** [comment]
На данный момент ситуация следующая: powershell пишет, что poetry установлен, cmd видит и poetry, и нужную версию питона, но при попытке сделать poetry install он вылетает, потому что отсутствуют файлы для python 3.9 (?!), mingw видит сразу две версии питона после export path, но после попытки запуска происходит пресловутый конфликт питонов, и консоль зависает
![image](https://user-images.githubusercontent.com/48051747/223652546-f47674fb-852e-455c-aa76-41a68a3a8858.png)
![image](https://user-images.githubusercontent.com/48051747/223652784-5080a0b9-f19c-4757-8d44-5cacdf7f98dc.png)
![image](https://user-images.githubusercontent.com/48051747/223654502-80f05838-24b3-4728-af71-5cb79f24c3b9.png)

**Comment by 78985** [comment]
Без export path консоль подвязана на версию питона 3.9.10 и вызывает именно её.
![image](https://user-images.githubusercontent.com/48051747/223655479-af7ddc23-2fec-4861-967e-e67058637103.png)

**Comment by 78985** [comment]
Предпринимал попытку удаления этой версии питона, но, как я и говорил, на неё подвязаны зависимости всех приложений, установленных на компе для работы, поэтому удалить её не представляется возможным

**Comment by FrCln** [comment]
Попробуйте `python -m poetry`, убедившись, что python именно 3.10.

А вообще, вам уже надо заканчивать работу над проектом, а вы все пытаетесь что-то запустить. Решите уже как-нибудь эту проблему для себя - используйте вместо poetry обычный pip + requirements.txt, перепишите все на python3.9 (там нужно только аннотации типов поправить) или еще что-то. Нужно решить задачу. Для этого можно использовать и другие средства.
